title = "泥土巢"
theme = "bootie-docs"
languageCode = "zh-CN"
baseURL = "http://nituchao.com"
copyright = "Copyright (c) 2017, nituchao | All rights reserved."
[params]
  author = "liang"
  metaDataFormat = "yaml"
  highlightStyle = "atelier-estuary-dark"
  withSitePosts = true
  repositoryUrl = "http://nituchao.com"
  description = "北国风光，千里冰封，万里雪飘。\n望长城内外，惟余莽莽；大河上下，顿失滔滔。\n山舞银蛇，原驰蜡象，欲与天公试比高。\n须晴日，看红装素裹，分外妖娆。\n江山如此多娇，引无数英雄竞折腰。\n惜秦皇汉武，略输文采；唐宗宋祖，稍逊风骚。\n一代天骄，成吉思汗，只识弯弓射大雕。\n俱往矣，数风流人物，还看今朝。"
[[params.mainMenu]]
    name = "文章"
    link = "post"
[[params.mainMenu]]
    name = "作品"
    link = "kk"
[[params.mainMenu]]
    name = "书单"
    link = "book"
[[params.mainMenu]]
    name = "设备"
    link = "device"
[[params.mainMenu]]
    name = "定律"
    link = "theorem"
[[params.mainMenu]]
    name = "关于"
    link = "about"
